// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcksnnAi5haFl7CPNUPUZu68lQELl-JP4',
    appId: '1:236014797490:web:00c8ea40edc6256b79bfab',
    messagingSenderId: '236014797490',
    projectId: 'sreerag-portfolio',
    authDomain: 'sreerag-portfolio.firebaseapp.com',
    storageBucket: 'sreerag-portfolio.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVkSgvWfm18jYLQ5ezh9m_Z2s11mm3O3Q',
    appId: '1:236014797490:android:d698efa6e0c5d7f779bfab',
    messagingSenderId: '236014797490',
    projectId: 'sreerag-portfolio',
    storageBucket: 'sreerag-portfolio.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvqWxVpMuUZIt7PTHx7y6nUkPYsRAok2A',
    appId: '1:236014797490:ios:f7f8a1ef97b48f3b79bfab',
    messagingSenderId: '236014797490',
    projectId: 'sreerag-portfolio',
    storageBucket: 'sreerag-portfolio.firebasestorage.app',
    iosBundleId: 'com.example.sreeragDev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvqWxVpMuUZIt7PTHx7y6nUkPYsRAok2A',
    appId: '1:236014797490:ios:f7f8a1ef97b48f3b79bfab',
    messagingSenderId: '236014797490',
    projectId: 'sreerag-portfolio',
    storageBucket: 'sreerag-portfolio.firebasestorage.app',
    iosBundleId: 'com.example.sreeragDev',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcksnnAi5haFl7CPNUPUZu68lQELl-JP4',
    appId: '1:236014797490:web:3319dded08f5d1bd79bfab',
    messagingSenderId: '236014797490',
    projectId: 'sreerag-portfolio',
    authDomain: 'sreerag-portfolio.firebaseapp.com',
    storageBucket: 'sreerag-portfolio.firebasestorage.app',
  );
}
